spring:
    application:
        name: catalog-service


swagger:
    title: "Catalog Service"
    version: "1.0"
    description: "Catalog Endpoints"
    package: catalogservice
    gateway-url: http://localhost:8080