server:
    port: 8081
spring:
    config:
        import: optional:configserver:http://localhost:8888
    application:
        name: identity-service
    flyway:
        enabled: true
        locations: classpath:migration
bizledger:
    jwt:
        secret: c3VwZXItc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmctZm9yLXNlY3VyaXR5
        expiration: 86400000
#debug: true

swagger:
    title: "Identity Service"
    version: "1.0"
    description: "Identity Endpoints"
    package: identityservice
    gateway-url: http://localhost:8080