server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native                              # native = read configs from local filesystem/classpath
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config-repo  # Config files stored in resources/config-repo/

management:
    endpoints:
        web:
            exposure:
                include: health,info,env
    endpoint:
        health:
            show-details: always

logging:
    level:
        org.springframework.cloud.config: DEBUG
